openapi: 3.0.3
info:
  title: Task Management API
  description: API for managing user tasks in the Todo Full-Stack Web Application
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Development server
  - url: https://api.todoapp.com/v1
    description: Production server

paths:
  /users/{user_id}/tasks:
    get:
      summary: Get user's tasks
      description: Retrieve a list of tasks for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The user's unique identifier
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of tasks to return
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Number of tasks to skip
        - name: completed
          in: query
          schema:
            type: boolean
          description: Filter by completion status
      responses:
        '200':
          description: List of tasks for the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  total:
                    type: integer
        '401':
          description: Unauthorized - Invalid or missing JWT
        '404':
          description: User not found
      security:
        - bearerAuth: []

    post:
      summary: Create a new task
      description: Create a new task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The user's unique identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized - Invalid or missing JWT
        '404':
          description: User not found
      security:
        - bearerAuth: []

  /users/{user_id}/tasks/{task_id}:
    get:
      summary: Get a specific task
      description: Retrieve details of a specific task for the user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The user's unique identifier
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The task's unique identifier
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '404':
          description: Task not found or doesn't belong to user
      security:
        - bearerAuth: []

    put:
      summary: Update a task
      description: Update properties of a specific task for the user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The user's unique identifier
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The task's unique identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized - Invalid or missing JWT
        '404':
          description: Task not found or doesn't belong to user
      security:
        - bearerAuth: []

    delete:
      summary: Delete a task
      description: Delete a specific task for the user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The user's unique identifier
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The task's unique identifier
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - Invalid or missing JWT
        '404':
          description: Task not found or doesn't belong to user
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - completed
        - created_at
        - updated_at
        - user_id
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the task
        title:
          type: string
          maxLength: 255
          description: Task title
        description:
          type: string
          description: Optional task description
        completed:
          type: boolean
          description: Whether the task is completed
        priority:
          type: string
          enum: [low, medium, high]
          default: medium
          description: Task priority level
        due_date:
          type: string
          format: date-time
          description: Optional due date for the task
        category:
          type: string
          maxLength: 100
          description: Optional category for the task
        tags:
          type: array
          items:
            type: string
          description: Optional tags for the task
        notification_settings:
          type: object
          description: Notification preferences for the task
        created_at:
          type: string
          format: date-time
          description: Timestamp when task was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when task was last updated
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns the task

    TaskCreateRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        priority:
          type: string
          enum: [low, medium, high]
          default: medium
        due_date:
          type: string
          format: date-time
        category:
          type: string
          maxLength: 100
        tags:
          type: array
          items:
            type: string
        notification_settings:
          type: object

    TaskUpdateRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        completed:
          type: boolean
        priority:
          type: string
          enum: [low, medium, high]
        due_date:
          type: string
          format: date-time
        category:
          type: string
          maxLength: 100
        tags:
          type: array
          items:
            type: string
        notification_settings:
          type: object